organization: Duke University Libraries
location: Durham, NC
google_maps: https://goo.gl/maps/zKuZb6KqEHZqaEMv6
event: DHRIFT deployment - test
date: 2024-12-01
end_date: 2025-12-01
workshopsuser: wsshaw
workshopsrepo: business_scrubs

url: 'https://scholarworks.duke.edu/'
logo: ''

intro: "I will teach you to boil away the living waters of language and make computers read the tea leaves. :-D"

motto: "0 1 2 3 4 5 6 7 8 9 a b c d e f"

register: 
  required: true
  url: 'https://registration/'
  show_button: true
  text: 'Register'

show_workshops: true

schedule:
  - date: 2024-12-31
    time: 9:00am
    title: "Seed Bells 101"
    workshop: seed-bells
    description: "How to purchase exactly the right size seed bell for your needs"
