organization: Duke University Libraries
location: Durham, NC
google_maps: https://goo.gl/maps/zKuZb6KqEHZqaEMv6
event: DHRIFT deployment - test
date: 2024-12-01
end_date: 2025-12-01

url: 'https://scholarworks.duke.edu/'
logo: ''

intro: "I will teach you to boil away the living waters of language and make computers read the tea leaves. :-D"

motto: "0 1 2 3 4 5 6 7 8 9 a b c d e f"

register: 
  required: true
  url: 'https://registration/'
  show_button: true
  text: 'Register'

show_workshops: true

schedule:
  - date: 2023-03-02
    time: 9:00am
    title: "Welcome to the DHRI"
    description: "This is the first day of the DHRI. We will introduce ourselves and the DHRI, 
    and discuss the goals of the institute."
  - date: 2023-03-02
    time: 11:00am
    title: "Introduction to the Command Line"
    # workshop: command-line
    description: "This workshop will introduce you to the command line, a text-based interface 
    for interacting with your computer. We will cover basic commands, file management, and 
    navigating the file system."
  - date: 2023-03-04
    time: 9:00am
    title: "Introduction to Git and GitHub"
    description: "This workshop will introduce you to Git and GitHub, a version control system 
    and a web-based hosting service for software development projects."
